almaas-main/bijouterie/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

# directions à partir de admin ( importé plus haut, multitude de chemins réglables offerts par le framework)

    path("admin/", admin.site.urls),

    # chemins que nous avons crées dans notre appli store

    path("", include("store.urls")),

    # Chemins pour effectuer des payements

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

almaas-main/store/urls.py
from store.forms import (
    LoginForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Routage

app_name = "store"

urlpatterns = [
    # Route page d'accueil
    path("", views.home, name="home"),
    # Routes pour les paiements et le panier
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("remove-cart/<int:cart_id>/", views.remove_cart, name="remove-cart"),
    path("plus-cart/<int:cart_id>/", views.plus_cart, name="plus-cart"),
    path("minus-cart/<int:cart_id>/", views.minus_cart, name="minus-cart"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("orders/", views.orders, name="orders"),
    # Routes pour les produits
    path("product/<slug:slug>/", views.detail, name="product-detail"),
    path("categories/", views.all_categories, name="all-categories"),
    path("<slug:slug>/", views.category_products, name="category-products"),
    # Routes d'authentification
    path("accounts/register/", views.registration_view, name="register"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(
            template_name="account/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("accounts/profile/", views.profile, name="profile"),
    path("accounts/add-address/", views.AddressView.as_view(), name="add-address"),
    path(
        "accounts/remove-address/<int:id>/", views.remove_address, name="remove-address"
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(next_page="store:login"),
        name="logout",
    ),
    path(
        "accounts/password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/password_change.html",
            form_class=PasswordChangeForm,
            success_url="/accounts/password-change-done/",
        ),
        name="password-change",
    ),
    path(
        "accounts/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="account/password_change_done.html"
        ),
        name="password-change-done",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset.html",
            form_class=PasswordResetForm,
            success_url="/accounts/password-reset/done/",
        ),
        name="password-reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset_confirm.html",
            form_class=SetPasswordForm,
            success_url="/accounts/password-reset-complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # path("product/test/", views.test, name="test"),
    # ADMIN DASHBOARD
    path("dashboard", views.dashboard, name="dashboard"),
    path(
        "dashboard/categories", views.dashboard_categories, name="dashboard-categories"
    ),
    path(
        "dashboard/categories/creation",
        views.dashboard_categorie_creation,
        name="dashboard-categorie-creation",
    ),
    path(
        "dashboard/categorie/<pk>/suppression/",
        views.dashboard_categorie_suppression,
        name="dashboard-categorie-suppression",
    ),
    path(
        "dashboard/categorie/modification/<pk>/",
        views.dashboard_categorie_modification,
        name="dashboard-categorie-modification",
    ),
    path("dashboard/produits", views.dashboard_produits, name="dashboard-produits"),
    path(
        "dashboard/produits/suppression/<pk>/",
        views.dashboard_produit_suppression,
        name="dashboard-produit-suppression",
    ),
    path(
        "dashboard/produits/modification/<pk>/",
        views.dashboard_produit_modification,
        name="dashboard-produit-modification",
    ),
    path(
        "dashboard/produits/creation/",
        views.dashboard_produit_creation,
        name="dashboard-produit-creation",
    ),
    path("dashboard/commandes", views.dashboard_commandes, name="dashboard-commandes"),
    path("search", views.search_view, name="search"),
]

almaas-main/store/views.py
from django.db.models import Q

from store.models import Address, Cart, Category, Order, Product
from django.shortcuts import redirect, render, get_object_or_404
from .forms import RegistrationForm, AddressForm, CategoryForm, ProductForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.conf import settings


# Création des vues
from .helpers import htmx_redirect


def home(request):
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    context = {
        "categories": categories,
        "products": products,
    }
    return render(request, "store/index.html", context)


def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.exclude(id=product.id).filter(
        is_active=True, category=product.category
    )
    context = {
        "product": product,
        "related_products": related_products,
    }
    return render(request, "store/detail.html", context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, "store/categories.html", {"categories": categories})


def category_products(request, slug):
    categorie = get_object_or_404(Category, slug=slug)
    produits = Product.objects.filter(is_active=True, category=categorie)
    categories = Category.objects.filter(is_active=True)
    context = {
        "category": categorie,
        "products": produits,
        "categories": categories,
    }
    return render(request, "store/category_products.html", context)


def registration_view(request):
    form = RegistrationForm()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request, "Félicitations! Inscription réussie!")
            form.save()
    return render(request, "account/register.html", {"form": form})


@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(
        request, "account/profile.html", {"addresses": addresses, "orders": orders}
    )


@method_decorator(login_required, name="dispatch")
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, "account/add_address.html", {"form": form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            utilisateur = request.user
            localite = form.cleaned_data["locality"]
            city = form.cleaned_data["city"]
            state = form.cleaned_data["state"]
            reg = Address(user=utilisateur, locality=localite, city=city, state=state)
            reg.save()
            messages.success(request, "Nouvelle adresse ajoutée.")
        return redirect("store:profile")


@login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Adresse supprimée.")
    return redirect("store:profile")


@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get("prod_id")
    product = get_object_or_404(Product, id=product_id)

    # On vérifie si le produit est dans le panier
    dans_le_panier = Cart.objects.filter(product=product_id, user=user)
    if dans_le_panier:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()

    return redirect("store:cart")


@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # afficher le total d'un panier frais de port compris

    amount = decimal.Decimal(0)
    shipping_amount = decimal.Decimal(10)

    # avoir le montant total en fonction du nombre de produits
    cp = [p for p in Cart.objects.all() if p.user == user]
    if cp:
        for p in cp:
            temp_amount = p.quantity * p.product.price
            amount += temp_amount

    addresses = Address.objects.filter(user=user)

    context = {
        "cart_products": cart_products,
        "amount": amount,
        "shipping_amount": shipping_amount,
        "total_amount": amount + shipping_amount,
        "addresses": addresses,
        "client_id": settings.CLIENT_ID,
    }
    return render(request, "store/cart.html", context)


@login_required
def remove_cart(request, cart_id):
    if request.method == "GET":
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
        messages.success(request, "Artice supprimé du panier !")
    return redirect("store:cart")


@login_required
def plus_cart(request, cart_id):
    if request.method == "GET":
        cp = get_object_or_404(Cart, id=cart_id)
        cp.quantity += 1
        cp.save()
    return redirect("store:cart")


@login_required
def minus_cart(request, cart_id):
    if request.method == "GET":
        cp = get_object_or_404(Cart, id=cart_id)

        # supprimer un produit du panier si decrementation et un seul
        if cp.quantity == 1:
            cp.delete()
        # decrementer son nombre sinon
        else:
            cp.quantity -= 1
            cp.save()
    return redirect("store:cart")


@login_required
def checkout(request):
    user = request.user
    address_id = request.GET.get("address")

    address = get_object_or_404(Address, id=address_id)
    cart = Cart.objects.filter(user=user)
    # proceed
    for c in cart:
        Order(user=user, address=address, product=c.product, quantity=c.quantity).save()
        c.delete()
    return redirect("store:orders")


@login_required
def orders(request):
    all_orders = Order.objects.filter(user=request.user).order_by("-ordered_date")
    return render(request, "store/orders.html", {"orders": all_orders})


def dashboard(
    request,
):
    return render(request, "admin/home.html")


def dashboard_categories(request):
    context = {"categories": Category.objects.all(), "form": CategoryForm()}

    return render(request, "admin/categories/list.html", context=context)


def dashboard_categorie_creation(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Catégorie bien enrgistrée")
        else:
            messages.error(request, f"{form.errors}")
    return redirect("store:dashboard-categories")


def dashboard_categorie_suppression(request, pk):
    categorie = get_object_or_404(Category, id=pk)
    categorie.delete()
    messages.success(request, "Catégorie supprimée !")
    return redirect("store:dashboard-categories")


def dashboard_categorie_modification(request, pk):
    categorie = get_object_or_404(Category, id=pk)
    form = CategoryForm(instance=categorie)
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Catégorie modifiée !")
            return redirect("store:dashboard-categories")
        else:
            messages.error(request, f"{form.errors}")
    return render(
        request,
        "admin/categories/modifcation.html",
        context={"form": form, "categorie": categorie},
    )


def dashboard_produits(request):
    return render(
        request,
        "admin/produits/list.html",
        context={"produits": Product.objects.all(), "form": ProductForm()},
    )


def dashboard_produit_suppression(request, pk):
    produit = get_object_or_404(Product, id=pk)
    produit.delete()
    messages.success(request, "Produit supprimé !")
    return redirect("store:dashboard-produits")


def dashboard_produit_modification(request, pk):
    produit = get_object_or_404(Product, id=pk)
    form = ProductForm(instance=produit)
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Produit modifiée !")
            return redirect("store:dashboard-produits")
        else:
            messages.error(request, f"{form.errors}")
    return render(
        request,
        "admin/produits/modification.html",
        context={"form": form, "produit": produit},
    )


def dashboard_produit_creation(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Produit bien enrgistré !")
        else:
            messages.error(request, f"{form.errors}")
    return redirect("store:dashboard-produits")


def dashboard_commandes(request):
    return render(request, "admin/commandes/list.html", {"orders": Order.objects.all()})


def search_view(request):

    if request.method == "POST":

        if request.POST.get("keyword") != "":

            # On vérifie si le mot clé de la recherche est une chaine de caractère vide

            # Recherche du mot clé dans le nom des produits ou dans la description du produit

            produits = Product.objects.filter(
                Q(title__icontains=request.POST.get("keyword"))
                | Q(short_description__icontains=request.POST.get("keyword"))
                | Q(category__title__icontains=request.POST.get("keyword")),
                is_active=True,
            )

            categories = Category.objects.filter(is_active=True)
            context = {
                "products": produits,
                "categories": categories,
            }
            return render(request, "partials/results.html", context)
    return htmx_redirect("store:home")

almaas-main/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block paypal %}
  <script src="https://www.paypal.com/sdk/js?client-id={{ client_id }}"></script>
{% endblock %}
    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Panier</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'store:home'%}">Accueil</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Panier</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Panier</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- table panier-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <!-- affichage de la réduction et du total après réduction -->
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Produit</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Prix</strong></th>
                        <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Réduction</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantité</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">€{{cart_product.product.price}}</p>
                      </td>
                    <td class="align-middle border-0">
                        <p class="mb-0 small"> € {{cart_product.product.montant_promo}} </p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantité</span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>

                      <td class="align-middle border-0">
                        <p class="mb-0 small">€{{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continuer mes achats</a></div>
                  <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="{% url 'store:home' %}">Passer au paiement<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">TOTAL</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Sous-total</strong><span class="text-muted small">€{{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Frais de livraison</strong><span class="text-muted small">+ €{{shipping_amount}}</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>€{{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Selectionnez votre adresse de livraison</h5>
                  
                  <form action="{% url 'store:checkout' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}"> <strong>Adresse {{forloop.counter}}</strong> <br>
                        ( {{address.locality}}, {{address.city}}, {{address.state}} )
                        </div>
                      {% endfor %}
                    {% endif %}

                    <!-- Set up a container element for the button -->
                    <div class="text-end" id="paypal-button-container"></div>

                    {% comment %} For Cash on Delivery {% endcomment %}
<!--                    <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class=""></i>Paiement lors de la livraison</button>-->
                    <button type="button" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class=""></i>Paiement lors de la livraison</button>

                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Votre panier est vide</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continuer mes achats </a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
{#    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>#}

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            // Apprence des boutons
            style: {
              layout: 'vertical',
              color:  'blue',
              shape:  'rect',
              label:  'pay'
            },
            // Parametrage de la transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        items: [],
                        amount: {
                            value: '{{total_amount}}',

                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Message de succès au client
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            },
            
            onError: function(err){
              return alert('Transaction failed !')
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}

almaas-main/templates/store/categories.html
{% extends 'base.html' %}
{% load static %}

      {% block content %}

      <div class="container">

        <section class="pt-5">
          <header class="text-center">
<!--            <p class="small text-muted small text-uppercase mb-1">phrase3</p>-->
            <h2 class="h5 text-uppercase mb-4">Découvrez nos catégories</h2>
          </header>
          <div class="row">
          {% if categories %}
            {% for category in categories %}

              <div class="col-md-4 mb-4 mb-md-5">
                <a class="category-item" href="{% url 'store:category-products' category.slug %}">
                  {% if category.category_image %}
                    <img class="img-fluid" src="{{ category.category_image.url }}" alt="{{ category.title }}">
                    {% else %}
                    <img class="img-fluid" src="{% static 'img/cat-img-1.jpg' %}" alt="{{ category.title }}">
                  {% endif %}
                  <strong class="category-item-title">{{ category.title }}</strong>
                </a>
              </div>
            
            {% endfor %}
          {% endif %}
          </div>
        </section>


        


        <section class="py-5 bg-light">
          <div class="container">
            <div class="row text-center">
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#delivery-time-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Livraison gratuite</h6>
                      <p class="text-small mb-0 text-muted">Livraison gratuite</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#helpline-24h-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">service 24 x 7 </h6>
                      <p class="text-small mb-0 text-muted">Livraison gratuite</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#label-tag-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Foire aux livres</h6>
                      <p class="text-small mb-0 text-muted">livraison gratuite</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>


        <!-- NEWSLETTER-->
        <section class="py-5">
          <div class="container p-0">
            <div class="row">
              <div class="col-lg-6 mb-3 mb-lg-0">
<!--                <h5 class="text-uppercase">phrase 1</h5>-->
<!--                <p class="text-small text-muted mb-0">phrase 2</p>-->
              </div>
              <div class="col-lg-6">
                <form action="#">
                  <div class="input-group flex-column flex-sm-row mb-3">
                    <input class="form-control form-control-lg py-3" type="email" placeholder=" Votre Email " aria-describedby="button-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-dark btn-block" id="button-addon2" type="submit">Inscription</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
      </div>

      {% endblock content %}