almaas-main/bijouterie/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

# directions à partir de admin ( importé plus haut, multitude de chemins réglables offerts par le framework)

    path("admin/", admin.site.urls),

    # chemins que nous avons crées dans notre appli store

    path("", include("store.urls")),

    # Chemins pour effectuer des payements

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

almaas-main/store/urls.py
from store.forms import (
    LoginForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Routage

app_name = "store"

urlpatterns = [
    # Route page d'accueil
    path("", views.home, name="home"),
    # Routes pour les paiements et le panier
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("remove-cart/<int:cart_id>/", views.remove_cart, name="remove-cart"),
    path("plus-cart/<int:cart_id>/", views.plus_cart, name="plus-cart"),
    path("minus-cart/<int:cart_id>/", views.minus_cart, name="minus-cart"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("orders/", views.orders, name="orders"),
    # Routes pour les produits
    path("product/<slug:slug>/", views.detail, name="product-detail"),
    path("categories/", views.all_categories, name="all-categories"),
    path("<slug:slug>/", views.category_products, name="category-products"),
    # Routes d'authentification
    path("accounts/register/", views.registration_view, name="register"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(
            template_name="account/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("accounts/profile/", views.profile, name="profile"),
    path("accounts/add-address/", views.AddressView.as_view(), name="add-address"),
    path(
        "accounts/remove-address/<int:id>/", views.remove_address, name="remove-address"
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(next_page="store:login"),
        name="logout",
    ),
    path(
        "accounts/password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/password_change.html",
            form_class=PasswordChangeForm,
            success_url="/accounts/password-change-done/",
        ),
        name="password-change",
    ),
    path(
        "accounts/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="account/password_change_done.html"
        ),
        name="password-change-done",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset.html",
            form_class=PasswordResetForm,
            success_url="/accounts/password-reset/done/",
        ),
        name="password-reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset_confirm.html",
            form_class=SetPasswordForm,
            success_url="/accounts/password-reset-complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # path("product/test/", views.test, name="test"),
    # ADMIN DASHBOARD
    path("dashboard", views.dashboard, name="dashboard"),
    path(
        "dashboard/categories", views.dashboard_categories, name="dashboard-categories"
    ),
    path(
        "dashboard/categories/creation",
        views.dashboard_categorie_creation,
        name="dashboard-categorie-creation",
    ),
    path(
        "dashboard/categorie/<pk>/suppression/",
        views.dashboard_categorie_suppression,
        name="dashboard-categorie-suppression",
    ),
    path(
        "dashboard/categorie/modification/<pk>/",
        views.dashboard_categorie_modification,
        name="dashboard-categorie-modification",
    ),
    path("dashboard/produits", views.dashboard_produits, name="dashboard-produits"),
    path(
        "dashboard/produits/suppression/<pk>/",
        views.dashboard_produit_suppression,
        name="dashboard-produit-suppression",
    ),
    path(
        "dashboard/produits/modification/<pk>/",
        views.dashboard_produit_modification,
        name="dashboard-produit-modification",
    ),
    path(
        "dashboard/produits/creation/",
        views.dashboard_produit_creation,
        name="dashboard-produit-creation",
    ),
    path("dashboard/commandes", views.dashboard_commandes, name="dashboard-commandes"),
    path("search", views.search_view, name="search"),
]

almaas-main/templates/partials/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="container mt-5 alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

almaas-main/templates/partials/results.html
{% load static %}
<div class="container">
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Boutique </h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Accueil </a></li>
                    <li class="breadcrumb-item"><a href="{% url 'store:all-categories' %}">Catégorie</a></li>
{#                    <li class="breadcrumb-item active" aria-current="page">{{category.title}}</li>#}
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
        <section class="py-5">
          <div class="container p-0">
            <div class="row">

              <div class="col-lg-3 order-2 order-lg-1">
                <h5 class="text-uppercase mb-4">Catégories</h5>

                {% if categories %}
                  {% for cat in categories %}
                    <a href="{% url 'store:category-products' cat.slug %}">
                      <div class="py-2 px-4 {% if category == cat %}bg-dark text-white {% else %}bg-light{% endif %} mb-3">
                        <strong class="small text-uppercase font-weight-bold">{{cat.title}}</strong>
                      </div>
                    </a>
                  {% endfor %}
                {% endif %}

              </div>
              <!-- SHOP LISTING-->
              <div class="col-lg-9 order-1 order-lg-2 mb-5 mb-lg-0">
                <div class="row mb-3 align-items-center">
                  <div class="col-lg-6 mb-2 mb-lg-0">
                    <p class="text-small text-muted mb-0">Voir 1–12 des résultats</p>
                  </div>
                  <div class="col-lg-6">
                    <ul class="list-inline d-flex align-items-center justify-content-lg-end mb-0">
                      <li class="list-inline-item text-muted mr-3"><a class="reset-anchor p-0" href="#"><i class="fas fa-th-large"></i></a></li>
                      <li class="list-inline-item text-muted mr-3"><a class="reset-anchor p-0" href="#"><i class="fas fa-th"></i></a></li>
                      <li class="list-inline-item">
                        <select class="selectpicker ml-auto" name="sorting" data-width="200" data-style="bs-select-form-control" data-title="Default sorting">
                          <option value="default">Tri par défaut</option>
                          <option value="popularity">Popularité</option>
                          <option value="low-high">Prix croissant</option>
                          <option value="high-low">Prix décroissant</option>
                        </select>
                      </li>
                    </ul>
                  </div>
                </div>

                <div class="row">

                  {% if products %}
                    {% for product in products %}

                      <!-- PRODUCT-->
                      <div class="col-lg-4 col-sm-6">
                        <div class="product text-center">
                          <div class="mb-3 position-relative">

                            <div class="badge text-white badge-"></div>

                            <a class="d-block" href="{% url 'store:product-detail' product.slug %}">
                              {% if product.product_image %}
                                <img class="img-fluid w-100" src="{{product.product_image.url}}" alt="{{product.title}}">
                              {% else %}
                                <img class="img-fluid w-100" src="{% static 'img/product-1.jpg' %}" alt="{{product.title}}">
                              {% endif %}
                            </a>

                            <div class="product-overlay">
                              <ul class="mb-0 list-inline">
                                <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-outline-dark" href="#"><i class="far fa-heart"></i></a></li>
                                <li class="list-inline-item m-0 p-0">
                                  {% comment %} <a class="btn btn-sm btn-dark" href="{% url 'store:add-to-cart' %}">Add to cart</a> {% endcomment %}

                                  <form action="{% url 'store:add-to-cart' %}">
                                    <input type="hidden" name="prod_id" value="{{product.id}}" id="product_id">
                                    <button type="submit" class="btn btn-sm btn-dark">Ajouter au panier</button>
                                  </form>

                                </li>
                              </ul>
                            </div>
                          </div>
                          <h6> <a class="reset-anchor" href="{% url 'store:product-detail' product.slug %}">{{product.title}}</a></h6>
                                {% if product.en_promo == True %}
                                    <p class="small text-muted">€  <strike>{{product.price}}</strike></p>

                                    <p class=alert-danger> - %  {{ product.taux }}</p>
                                    <p class="alert-warning"> € {{ product.prix_effectif }}</p>
                                {% endif %}
                                {% if product.en_promo == False %}
                                    <p class="small text-muted"> € {{ product.price }}</p>
                                {% endif %}

                        </div>
                      </div>

                    {% endfor %}
                  {% endif %}


                </div>

              </div>
            </div>
          </div>
        </section>
      </div>