almaas-main/bijouterie/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

# directions à partir de admin ( importé plus haut, multitude de chemins réglables offerts par le framework)

    path("admin/", admin.site.urls),

    # chemins que nous avons crées dans notre appli store

    path("", include("store.urls")),

    # Chemins pour effectuer des payements

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

almaas-main/store/urls.py
from store.forms import (
    LoginForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Routage

app_name = "store"

urlpatterns = [
    # Route page d'accueil
    path("", views.home, name="home"),
    # Routes pour les paiements et le panier
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("remove-cart/<int:cart_id>/", views.remove_cart, name="remove-cart"),
    path("plus-cart/<int:cart_id>/", views.plus_cart, name="plus-cart"),
    path("minus-cart/<int:cart_id>/", views.minus_cart, name="minus-cart"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("orders/", views.orders, name="orders"),
    # Routes pour les produits
    path("product/<slug:slug>/", views.detail, name="product-detail"),
    path("categories/", views.all_categories, name="all-categories"),
    path("<slug:slug>/", views.category_products, name="category-products"),
    # Routes d'authentification
    path("accounts/register/", views.registration_view, name="register"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(
            template_name="account/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("accounts/profile/", views.profile, name="profile"),
    path("accounts/add-address/", views.AddressView.as_view(), name="add-address"),
    path(
        "accounts/remove-address/<int:id>/", views.remove_address, name="remove-address"
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(next_page="store:login"),
        name="logout",
    ),
    path(
        "accounts/password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/password_change.html",
            form_class=PasswordChangeForm,
            success_url="/accounts/password-change-done/",
        ),
        name="password-change",
    ),
    path(
        "accounts/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="account/password_change_done.html"
        ),
        name="password-change-done",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset.html",
            form_class=PasswordResetForm,
            success_url="/accounts/password-reset/done/",
        ),
        name="password-reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset_confirm.html",
            form_class=SetPasswordForm,
            success_url="/accounts/password-reset-complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # path("product/test/", views.test, name="test"),
    # ADMIN DASHBOARD
    path("dashboard", views.dashboard, name="dashboard"),
    path(
        "dashboard/categories", views.dashboard_categories, name="dashboard-categories"
    ),
    path(
        "dashboard/categories/creation",
        views.dashboard_categorie_creation,
        name="dashboard-categorie-creation",
    ),
    path(
        "dashboard/categorie/<pk>/suppression/",
        views.dashboard_categorie_suppression,
        name="dashboard-categorie-suppression",
    ),
    path(
        "dashboard/categorie/modification/<pk>/",
        views.dashboard_categorie_modification,
        name="dashboard-categorie-modification",
    ),
    path("dashboard/produits", views.dashboard_produits, name="dashboard-produits"),
    path(
        "dashboard/produits/suppression/<pk>/",
        views.dashboard_produit_suppression,
        name="dashboard-produit-suppression",
    ),
    path(
        "dashboard/produits/modification/<pk>/",
        views.dashboard_produit_modification,
        name="dashboard-produit-modification",
    ),
    path(
        "dashboard/produits/creation/",
        views.dashboard_produit_creation,
        name="dashboard-produit-creation",
    ),
    path("dashboard/commandes", views.dashboard_commandes, name="dashboard-commandes"),
    path("search", views.search_view, name="search"),
]

almaas-main/templates/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard -ALMAAS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- CSS Files -->

  <link href="{% static 'admin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'admin/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'admin/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'admin/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'admin/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">
    {% block addCss %}

    {% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'store:home' %}" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span class="d-none d-lg-block" style="color: #dcb14a">ALMAAS</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
    {% comment %}  <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->{% endcomment %}

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'store:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Catégories</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'store:dashboard-categories' %}">
              <i class="bi bi-circle"></i><span>Toutes les catégories</span>
            </a>
          </li>
         {% comment %} <li>
            <a href="{% url 'store:dashboard-categorie-creation' %}">
              <i class="bi bi-circle"></i><span>Nouvelle catégorie</span>
            </a>
          </li>{% endcomment %}
        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Produits</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'store:dashboard-produits' %}">
              <i class="bi bi-circle"></i><span>Tout les produits </span>
            </a>
          </li>
          {% comment %}<li>
            <a href="{% url 'store:dashboard-produit-creation' %}">
              <i class="bi bi-circle"></i><span>Nouveaux produits</span>
            </a>
          </li>{% endcomment %}
        </ul>
      </li><!-- End Forms Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-bar-chart"></i><span>Commandes</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'store:dashboard-commandes' %}">
              <i class="bi bi-circle"></i><span> Toutes les commandes</span>
            </a>
          </li>
        </ul>
      </li><!-- End Charts Nav -->
    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
  {% if messages %}
          <ul class="messages message-list rounded-pill">
              {% for message in messages %}
               <div class="alert text-sm-center alert-dismissable {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}">
                  {{message | safe}}<button type="button" class="btn btn-sm close text-center" data-bs-dismiss="alert" aria-hidden="true">&nbsp;&times;</button>
               </div>
              {% endfor %}
          </ul>
        {% endif %}
    {% block admin_content %}

    {% endblock %}
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% block addJS %}

  {% endblock %}
  <!-- Vendor JS Files -->
{#  <script src="{% static 'admin/apexcharts/apexcharts.min.js' %}"></script>#}
  <script src="{% static 'admin/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'admin/chart.js/chart.min.js' %}"></script>
{#  <script src="{% static 'admin/echarts/echarts.min.js' %}"></script>#}
  <script src="{% static 'admin/quill/quill.min.js' %}"></script>
  <script src="{% static 'admin/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'admin/tinymce/tinymce.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

almaas-main/templates/base.html
{% load static %}
{% load django_htmx %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}Bijouterie Almass{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.gold.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <!--HTMX-->
{#    <script src="{% static 'htmx/htmx.org@1.7.0' %}" defer></script>#}
      <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    {% django_htmx_script %}
    {% block paypal %}

    {% endblock %}


  </head>
  <body>

    <div class="page-holder">
      {% include 'navbar.html' %}
        <div id="search-results">
            {% block content %}

            {% endblock content %}
        </div>
      {% block payment-gateway %}{% endblock payment-gateway %}
      
      {% include 'footer.html' %}
      {% include 'scripts.html' %}
    </div>

almaas-main/templates/footer.html
<footer class="bg-dark text-white">
        <div class="container py-4">
          <div class="row py-5">
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Service client</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#">Aide et Contact</a></li>
                <li><a class="footer-link" href="#">Remboursements et retours</a></li>
                <li><a class="footer-link" href="#">Nos boutiques en ligne</a></li>
                <li><a class="footer-link" href="#"></a></li>
              </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Notre entreprise</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#">Ce que nous faisons</a></li>
                <li><a class="footer-link" href="#">Services</a></li>
                <li><a class="footer-link" href="#">Derniers posts</a></li>
                <li><a class="footer-link" href="#">Questions frequentes</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h6 class="text-uppercase mb-3">Reseaux sociaux</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#">Twitter</a></li>
                <li><a class="footer-link" href="#">Instagram</a></li>
                <li><a class="footer-link" href="#">Tumblr</a></li>
                <li><a class="footer-link" href="#">Pinterest</a></li>
              </ul>
            </div>
          </div>
          <div class="border-top pt-4" style="border-color: #1d1d1d !important">
            <div class="row">
              <div class="col-lg-6">
                <p class="small text-muted mb-0">Mai 2022 Tous Droits reserves</p>
              </div>
              <div class="col-lg-6 text-lg-right">
                <p class="small text-muted mb-0">Site web avec <a class="text-white reset-anchor" href="#" target="_blank"> Mehdi et Sami</a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>

almaas-main/templates/navbar.html
{% load static %}

<!-- navbar-->
      <header class="header bg-white">
        <div class="container px-0 px-lg-3">
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'store:home' %}"><span class="font-weight-bold text-uppercase text-dark">Almaass</span></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <!-- Link--><a class="nav-link active" href="{% url 'store:home' %}">Accueil</a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}">{{cat_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories' %}">Toutes</a>
                  </div><!--a surveiller-->
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'store:dashboard' %}">Dashboard</a>
                </li>
                {% endif %}
              </ul>
              <ul class="navbar-nav ml-auto"> 
                {% if request.user.is_authenticated %}

                    <li class="nav-item">
                        <form hx-post="{% url 'store:search' %}" hx-target="#search-results">
                             {% csrf_token %}
                            <input class="form-control form-control-sm rounded-lg" type="search" name="keyword" placeholder="Rechercher un produit ... ">
{#                            <span class="htmx-indicator "><img src="https://htmx.org/img/bars.svg"/></span>#}
                        </form>
                    </li>


                  <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Panier<small class="text-gray">({{cart_items.count}})</small></a></li>
                  <li class="nav-item"><a class="nav-link" href="#"> <i class="far fa-heart mr-1"></i><small class="text-gray"> (0)</small></a></li>
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="fas fa-user-alt mr-1 text-gray"></i>Mon compte </a></li> {% endcomment %}

                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i>Mon compte</a></a>
                  
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}">Mon profil</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}">Panier</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}">Commandes</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:password-change' %}">Reinitialiser le mot de passe</a>

                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:logout' %}">Deconnexion</a>
                  </div><!-- a surveiller-->
                   </li>
                {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}">Connexion</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:register' %}">Enregistrement</a></li>
                {% endif %}   
              </ul>
            </div>
          </nav>
        </div>
      </header>

almaas-main/templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'jquery/jquery.min.js' %}"></script>
      <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>

      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>

        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }

        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>